spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallback/product
            # ✅ Tạm thời tắt Retry để test đếm thủ công
            # - name: Retry
            #   args:
            #     retries: 3
            #     statuses: BAD_GATEWAY
            #     methods: GET
            - name: RequestSize
              args:
                maxSize: 5000

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/order
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: customerCircuitBreaker
                fallbackUri: forward:/fallback/customer
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentCircuitBreaker
                fallbackUri: forward:/fallback/payment
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: POST,GET

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryCircuitBreaker
                fallbackUri: forward:/fallback/inventory
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: POST,GET

        - id: shipping-service
          uri: lb://shipping-service
          predicates:
            - Path=/shipping/**
          filters:
            - name: CircuitBreaker
              args:
                name: shippingCircuitBreaker
                fallbackUri: forward:/fallback/shipping
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: POST,GET
